baseURL: "https://www.btcpay.sk" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: btcpay.sk
paginate: 5
theme: PaperModX

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

defaultContentLanguage: sk

languages:
    sk:
        languageName: "Slovenčina"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Archív
                  url: archiv
                  weight: 5
                - name: Vyhľadávanie
                  url: search/
                  weight: 10
                - name: Tagy
                  url: tags/
                  weight: 10
                - name: Kategórie
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "btcpay.sk - Krypto platby rýchlo a pohodlnne"
    author: btcpay.sk
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    # ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archiv
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "btcpay.sk"
        Content: >
            Vitajte na stránkach komunitného BtcPayServer-a.

            - <b>Pozor! Stránky a brána momentálne fungujú v testovacej prevádzke.</b> Verejné registrácie nie sú povolené a obsah webu nie je skompletizovaný. V prípade že sa chcete do testu zapojiť, kontaktujte nás emailom.

            - Misia **btcpay.sk** je rozšíriť adopciu platieb kryptomenami. Prevádzkujeme verejný BtcPayServer, ktorý môžu obchodníci (alebo ktokoľvek iný) integrovať na svoj webshop bez technických znalostí.

            - V prípade záujmu si môžete prečítať <a href='navod'><b>návod ako na to</b></a>, čo to o <a href='bezpecnost'><b>bezpečnosti riešenia</b></a> ako aj informácie o zákonoch a <a href='legal'><b>právnej stránke</b></a> riešenia platieb cez BtcPayServer.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/btcpay_sk"
        - name: facebook
          url: "https://fb.me/btcpay.sk"
        - name: email
          url: "mailto:ahoj@btcpay.sk"
        - name: github
          url: "https://github.com/btcpaysk"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://github.com/btcpaysk/btcpay.sk/content"
        Text: "Navrhni zmeny" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
